In [1]:
# def cleaning():
import pandas as p
import numpy as n
import matplotlib.pyplot as m
data=p.read_csv("Car-details-v3.csv")

data=data.dropna()
backup=data

In [2]:
data.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
mileage          0
engine           0
max_power        0
torque           0
seats            0
dtype: int64

In [3]:
data['name']=data['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [4]:
data.reset_index(drop=True)

name  year  selling_price  km_driven    fuel  \
0       Maruti Swift Dzire  2014         450000     145500  Diesel   
1          Skoda Rapid 1.5  2014         370000     120000  Diesel   
2     Honda City 2017-2020  2006         158000     140000  Petrol   
3       Hyundai i20 Sportz  2010         225000     127000  Diesel   
4         Maruti Swift VXI  2007         130000     120000  Petrol   
...                    ...   ...            ...        ...     ...   
7901     Hyundai i20 Magna  2013         320000     110000  Petrol   
7902    Hyundai Verna CRDi  2007         135000     119000  Diesel   
7903    Maruti Swift Dzire  2009         382000     120000  Diesel   
7904       Tata Indigo CR4  2013         290000      25000  Diesel   
7905       Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner     mileage   engine  \
0     Individual       Manual           First Owner   23.4 kmpl  1248 CC   
1     Individual       Manual          Second Owner  21.14 kmpl  1498 CC   
2     Individual       Manual           Third Owner   17.7 kmpl  1497 CC   
3     Individual       Manual           First Owner   23.0 kmpl  1396 CC   
4     Individual       Manual           First Owner   16.1 kmpl  1298 CC   
...          ...          ...                   ...         ...      ...   
7901  Individual       Manual           First Owner   18.5 kmpl  1197 CC   
7902  Individual       Manual  Fourth & Above Owner   16.8 kmpl  1493 CC   
7903  Individual       Manual           First Owner   19.3 kmpl  1248 CC   
7904  Individual       Manual           First Owner  23.57 kmpl  1396 CC   
7905  Individual       Manual           First Owner  23.57 kmpl  1396 CC   

       max_power                     torque  seats  
0         74 bhp             190Nm@ 2000rpm    5.0  
1     103.52 bhp        250Nm@ 1500-2500rpm    5.0  
2         78 bhp      12.7@ 2,700(kgm@ rpm)    5.0  
3         90 bhp   22.4 kgm at 1750-2750rpm    5.0  
4       88.2 bhp      11.5@ 4,500(kgm@ rpm)    5.0  
...          ...                        ...    ...  
7901   82.85 bhp           113.7Nm@ 4000rpm    5.0  
7902     110 bhp  24@ 1,900-2,750(kgm@ rpm)    5.0  
7903    73.9 bhp             190Nm@ 2000rpm    5.0  
7904      70 bhp        140Nm@ 1800-3000rpm    5.0  
7905      70 bhp        140Nm@ 1800-3000rpm    5.0  

[7906 rows x 13 columns]

In [5]:
x=data["fuel"].to_numpy()
x=list(x)
for i in range(len(x)):
    if x[i]=="Petrol":
        x[i]=0
    elif x[i]=="Diesel":
        x[i]=1
    elif x[i]=="LPG":
        x[i]=2
    elif x[i]=="CNG":
        x[i]=3
data.fuel=x
#0- petrol,1-diesel,2-lpg,3-cng

In [6]:
data.replace({"seller_type":{"Individual":0,"Dealer":1,"Trustmark Dealer":2}},inplace=True)
data.replace({"transmission":{"Manual":0,"Automatic":1}},inplace=True)
data.mileage=data.mileage.str.split(" ").str.get(0).astype(float)
data.replace({"owner":{"First Owner":0,"Second Owner":1,"Third Owner":2,"Fourth & Above Owner":3,"Test Drive Car":4}},inplace=True)
data.engine=data.engine.str.split(" ").str.get(0).astype(int)
data.max_power=data.max_power.str.split(" ").str.get(0).astype(float)
del data['torque']
data.reset_index(drop=True)

# data.transmission.value_counts()


name  year  selling_price  km_driven  fuel  seller_type  \
0       Maruti Swift Dzire  2014         450000     145500     1            0   
1          Skoda Rapid 1.5  2014         370000     120000     1            0   
2     Honda City 2017-2020  2006         158000     140000     0            0   
3       Hyundai i20 Sportz  2010         225000     127000     1            0   
4         Maruti Swift VXI  2007         130000     120000     0            0   
...                    ...   ...            ...        ...   ...          ...   
7901     Hyundai i20 Magna  2013         320000     110000     0            0   
7902    Hyundai Verna CRDi  2007         135000     119000     1            0   
7903    Maruti Swift Dzire  2009         382000     120000     1            0   
7904       Tata Indigo CR4  2013         290000      25000     1            0   
7905       Tata Indigo CR4  2013         290000      25000     1            0   

      transmission  owner  mileage  engine  max_power  seats  
0                0      0    23.40    1248      74.00    5.0  
1                0      1    21.14    1498     103.52    5.0  
2                0      2    17.70    1497      78.00    5.0  
3                0      0    23.00    1396      90.00    5.0  
4                0      0    16.10    1298      88.20    5.0  
...            ...    ...      ...     ...        ...    ...  
7901             0      0    18.50    1197      82.85    5.0  
7902             0      3    16.80    1493     110.00    5.0  
7903             0      0    19.30    1248      73.90    5.0  
7904             0      0    23.57    1396      70.00    5.0  
7905             0      0    23.57    1396      70.00    5.0  

[7906 rows x 12 columns]

In [7]:
data.describe()

year  selling_price     km_driven         fuel  seller_type  \
count  7906.000000   7.906000e+03  7.906000e+03  7906.000000  7906.000000   
mean   2013.983936   6.498137e+05  6.918866e+04     0.572350     0.199722   
std       3.863695   8.135827e+05  5.679230e+04     0.541406     0.468575   
min    1994.000000   2.999900e+04  1.000000e+00     0.000000     0.000000   
25%    2012.000000   2.700000e+05  3.500000e+04     0.000000     0.000000   
50%    2015.000000   4.500000e+05  6.000000e+04     1.000000     0.000000   
75%    2017.000000   6.900000e+05  9.542500e+04     1.000000     0.000000   
max    2020.000000   1.000000e+07  2.360457e+06     3.000000     2.000000   

       transmission        owner      mileage       engine    max_power  \
count   7906.000000  7906.000000  7906.000000  7906.000000  7906.000000   
mean       0.131672     0.447255    19.419861  1458.708829    91.587374   
std        0.338155     0.710854     4.036263   503.893057    35.747216   
min        0.000000     0.000000     0.000000   624.000000    32.800000   
25%        0.000000     0.000000    16.780000  1197.000000    68.050000   
50%        0.000000     0.000000    19.300000  1248.000000    82.000000   
75%        0.000000     1.000000    22.320000  1582.000000   102.000000   
max        1.000000     4.000000    42.000000  3604.000000   400.000000   

             seats  
count  7906.000000  
mean      5.416393  
std       0.959208  
min       2.000000  
25%       5.000000  
50%       5.000000  
75%       5.000000  
max      14.000000

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7906 entries, 0 to 8127
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           7906 non-null   object 
 1   year           7906 non-null   int64  
 2   selling_price  7906 non-null   int64  
 3   km_driven      7906 non-null   int64  
 4   fuel           7906 non-null   int64  
 5   seller_type    7906 non-null   int64  
 6   transmission   7906 non-null   int64  
 7   owner          7906 non-null   int64  
 8   mileage        7906 non-null   float64
 9   engine         7906 non-null   int32  
 10  max_power      7906 non-null   float64
 11  seats          7906 non-null   float64
dtypes: float64(3), int32(1), int64(7), object(1)
memory usage: 772.1+ KB


# MODEL

In [32]:
x=data[['name','year','fuel']]
# x=data.drop(columns='selling_price')
y=data['selling_price']

In [33]:
# x.reset_index(drop=True)
# y.reset_index(drop=True)

In [34]:
data.describe()

year  selling_price     km_driven         fuel  seller_type  \
count  7905.000000   7.905000e+03  7.905000e+03  7905.000000  7905.000000   
mean   2013.983555   6.486309e+05  6.919362e+04     0.572423     0.199747   
std       3.863791   8.068074e+05  5.679418e+04     0.541402     0.468599   
min    1994.000000   2.999900e+04  1.000000e+00     0.000000     0.000000   
25%    2012.000000   2.700000e+05  3.500000e+04     0.000000     0.000000   
50%    2015.000000   4.500000e+05  6.000000e+04     1.000000     0.000000   
75%    2017.000000   6.900000e+05  9.550000e+04     1.000000     0.000000   
max    2020.000000   7.200000e+06  2.360457e+06     3.000000     2.000000   

       transmission        owner      mileage       engine    max_power  \
count   7905.000000  7905.000000  7905.000000  7905.000000  7905.000000   
mean       0.131562     0.447312    19.417004  1458.644276    91.548359   
std        0.338036     0.710881     4.028519   503.892238    35.580745   
min        0.000000     0.000000     0.000000   624.000000    32.800000   
25%        0.000000     0.000000    16.780000  1197.000000    68.050000   
50%        0.000000     0.000000    19.300000  1248.000000    82.000000   
75%        0.000000     1.000000    22.320000  1582.000000   102.000000   
max        1.000000     4.000000    33.440000  3604.000000   282.000000   

             seats  
count  7905.000000  
mean      5.416572  
std       0.959137  
min       2.000000  
25%       5.000000  
50%       5.000000  
75%       5.000000  
max      14.000000

In [35]:
data=data[data['selling_price']<10000000]

In [36]:
# data['year'].unique()

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [41]:
ohe=OneHotEncoder()
ohe.fit(x[['name','year','fuel']])

OneHotEncoder()

In [42]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','year','fuel']),
                                    remainder='passthrough')

In [43]:
lr=LinearRegression()

In [44]:
pipe=make_pipeline(column_trans,lr)

In [45]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Ambassador CLASSIC 1500', 'Ambassador Classic 2000',
       'Ambassador Grand 1500', 'Ambassador Grand 2000',
       'Ashok Leyland Stile', 'Audi A3 35', 'Audi A3 40', 'Audi A4 1.8',
       'Audi A4 2.0', 'Audi A4 35', 'Audi A6 2.0', 'Audi A6 35',
       'Audi Q3 2.0', 'Au...
       'Volkswagen Vento Petrol', 'Volvo S60 D4', 'Volvo S90 D4',
       'Volvo V40 Cross', 'Volvo V40 D3', 'Volvo XC40 D4',
       'Volvo XC60 Inscription'], dtype=object),
                                                                            array([1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2020], dtype=int64),
                          

In [46]:
y_pred=pipe.predict(x_test)
y_pred

array([ 64082.96817784, 432209.70395028, 666333.13795357, ...,
       184466.9910751 , 254383.66938751, 460820.32732855])

In [47]:
r2_score(y_test,y_pred)

0.9621688515317008

In [48]:
scores=[]
for i in range(100):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_pred=pipe.predict(x_test)
    scores.append(r2_score(y_test,y_pred))

In [49]:
n.argmax(scores)

77

In [50]:
scores[n.argmax(scores)]


0.9747958547046949

In [51]:
# data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=i)
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(x_train,y_train)
y_pred=pipe.predict(x_test)
(r2_score(y_test,y_pred))

0.8833404687675454

In [52]:
import pickle

In [53]:
pickle.dump(pipe,open('LinearRegressionModel (2).pkl','wb'))

In [54]:
backup

name  year  selling_price  km_driven  fuel  seller_type  \
0       Maruti Swift Dzire  2014         450000     145500     1            0   
1          Skoda Rapid 1.5  2014         370000     120000     1            0   
2     Honda City 2017-2020  2006         158000     140000     0            0   
3       Hyundai i20 Sportz  2010         225000     127000     1            0   
4         Maruti Swift VXI  2007         130000     120000     0            0   
...                    ...   ...            ...        ...   ...          ...   
8123     Hyundai i20 Magna  2013         320000     110000     0            0   
8124    Hyundai Verna CRDi  2007         135000     119000     1            0   
8125    Maruti Swift Dzire  2009         382000     120000     1            0   
8126       Tata Indigo CR4  2013         290000      25000     1            0   
8127       Tata Indigo CR4  2013         290000      25000     1            0   

      transmission  owner  mileage  engine  max_power  seats  
0                0      0    23.40    1248      74.00    5.0  
1                0      1    21.14    1498     103.52    5.0  
2                0      2    17.70    1497      78.00    5.0  
3                0      0    23.00    1396      90.00    5.0  
4                0      0    16.10    1298      88.20    5.0  
...            ...    ...      ...     ...        ...    ...  
8123             0      0    18.50    1197      82.85    5.0  
8124             0      3    16.80    1493     110.00    5.0  
8125             0      0    19.30    1248      73.90    5.0  
8126             0      0    23.57    1396      70.00    5.0  
8127             0      0    23.57    1396      70.00    5.0  

[7906 rows x 12 columns]

In [55]:
pipe.predict(p.DataFrame([['Maruti Swift Dzire',2014,1]],columns=['name','year','fuel']))

array([472148.00683677])

In [ ]:
# pipe.predict(p.DataFrame(columns=x_test.columns,data=n.array(['Ambassador CLASSIC 1500',1994,'Petrol']).reshape(1,3)))